[package]
name = "mdbook-toc"
version = "0.11.1"
authors = ["Jan-Erik Rediger <janerik@fnordig.de>"]
description = "mdbook preprocessor to add Table of Contents"
license = "MPL-2.0"
homepage = "https://github.com/badboy/mdbook-toc"
repository = "https://github.com/badboy/mdbook-toc"
edition = "2018"
rust-version = "1.58"

[dependencies]
mdbook = "0.4.27"
pulldown-cmark = "0.9.1"
log = "0.4.11"
clap = { version = "4.0.29", features = ["cargo"] }
serde_json = "1.0.57"
toml = "0.5.11"

[dev-dependencies]
pretty_assertions = "1.0.0"
env_logger = "0.10.0"
